# cf. https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

variables:
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  CURRENT_COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME == "main"

  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
    - docker build -f docker/php/Dockerfile --pull --tag $LATEST_IMAGE --tag $CURRENT_COMMIT_IMAGE .
    - docker push $LATEST_IMAGE
    - docker push $CURRENT_COMMIT_IMAGE